platform :ios, '9.0'
use_frameworks!
target 'UnderTheKitchen-Swift' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh', '~> 3.1.13'
#pod 'YYModel', '~> 1.0.4'
#pod 'IQKeyboardManager', '~> 5.0.7'
#pod 'Reachability', '~> 3.2'
#pod 'BlocksKit', '~> 2.2.5'
#pod 'ZBarSDK', '~> 1.3.1'
pod 'SDCycleScrollView'
#pod 'SDWebImage', '~> 3.8.1'
#pod 'SnapKit', '~> 3.2.0'
#pod 'SSZipArchive', '~> 2.0.4'
#pod 'TZImagePickerController'
#pod 'HUPhotoBrowser'
#pod 'LGAlertView'
#pod 'Alamofire', '~> 4.5.1'
#pod 'Kingfisher', '~> 3.1.1'
#pod 'Toast', '~> 2.4'
#pod 'FMDB', '~> 2.6.2'
#pod 'Masonry', '~> 1.0.2'
#pod 'SSKeychain', '~> 1.2.3'
#pod 'SwiftyJSON', '~> 3.1.4'
end





